function SetKernelParameter()

 phkernel = figure('units','pixels','position', [50 100 300 400],...
   'tag','GUI', 'name','Kernel Pameter Setup',...
   'menubar','none','numbertitle','off');

uicontrol(phkernel, 'Style', 'text', 'String', 'R ', 'HorizontalAlignment', 'center',...
					'Units','Normalize','Position', [0.05,.67,.4,.1], 'BackgroundColor', [.8,.8,.8]);
psfR = uicontrol(phkernel, 'Style', 'edit', ...
					'String', '4', 'Callback', @UpdateParameter, ...
					'Units','Normalize','Position', [0.55,.72,.4,.1]);
uicontrol('Parent', phkernel, 'Style', 'text', 'String', 'W ', 'HorizontalAlignment', 'center',...
					'Units','Normalize','Position', [0.05,.52,.4,.1], 'BackgroundColor', [.8,.8,.8]);
psfW = uicontrol('Parent', phkernel, 'Style', 'edit', ...
					'String', '0.8', 'Callback', @UpdateParameter, ...
					'Units','Normalize','Position', [0.55,.57,.4,.1]);
uicontrol('Parent',phkernel, 'Style', 'text', 'String', 'Radius ', 'HorizontalAlignment', 'center',...
					'Units','Normalize','Position', [0.05,.38,.4,.1], 'BackgroundColor', [.8,.8,.8]);
psfRadius = uicontrol('Parent',phkernel, 'Style', 'edit', ...
					'String', '2', 'Callback', @UpdateParameter, ...
					'Units','Normalize','Position', [0.55,.42,.4,.1]);
uicontrol('Parent',phkernel, 'Style', 'text', 'String', 'Zeta S', 'HorizontalAlignment', 'center',...
					'Units','Normalize','Position', [0.05,.22,.4,.1], 'BackgroundColor', [.8,.8,.8]);
psfZetaS = uicontrol('Parent',phkernel, 'Style', 'edit', ...
					'Units','Normalize','String', '1', 'Callback', @UpdateParameter, ...
					'Position', [0.55,.27,.4,.1]);
uicontrol(phkernel, 'Style', 'text', 'String', 'Dictionary Size ', 'HorizontalAlignment', 'center',...
					'Units','Normalize','Position', [0.05,.82,.4,.1], 'BackgroundColor', [.8,.8,.8]);
psfM = uicontrol(phkernel, 'Style', 'edit', ...
					'String', '20', 'Callback', @UpdateParameter, ...
					'Units','Normalize','Position', [0.55,.87,.4,.1]);
                
Pcn.kern = uicontrol('Parent',phkernel, 'Style','pushbutton', 'Units', 'Normalized','Position',[.05 .05 .9 .15], ...
                    'String','Kernel Display','Callback', 'KernelDisplay');  
                
kernparas=struct('R',4,'W',0.8,'radius',2,'zetap',0.8,'dicsize',20);        
                
                
                
   function  UpdateParameter(hObject,eventdata)
     kernparas.R = str2num(get(psfR, 'String'));
	 kernparas.W = str2num(get(psfW, 'String'));
	 kernparas.radius = str2num(get(psfRadius, 'String'));
     kernparas.zetap = str2num(get(psfZetaS, 'String'));
     kernparas.dicsize= str2num(get(psfM, 'String'));
     assignin('base', 'kernparas', kernparas);
   end       
                         
                
end